spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/bootdemo?&amp;useUnicode=true&amp;characterEncoding=utf-8
    data-username: demo
    data-password: demo
    driver-class-name: com.mysql.jdbc.Driver
  session:
    store-type: redis
  redis:
    host: 127.0.0.1
    password:
    database: 1
    port: 6379
  thymeleaf:
    cache: false
server:
  port: 8080
